salmar/hymns/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from hymns.views import HymnFormView, HymnView


urlpatterns = patterns(
    'hymns.views',
    url('^$', HymnView.as_view(), name='hymn'),
    url('^(?P<hymn_id>\d+)/$', HymnView.as_view(), name='view_hymn'),
    url('^add/$', login_required(HymnFormView.as_view()), name='add_hymn'),
    url('^edit/(?P<hymn_id>\d+)/$', login_required(HymnFormView.as_view()), name='edit_hymn'),
)

salmar/salmar/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView

from views import login_user, logout_user

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', RedirectView.as_view(url='/hymns/'), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hymns/', include('hymns.urls')),
    url(r'^logout/', logout_user, name='logout'),
    url(r"^(?P<page>.*?)login/{0,1}$", login_user, name="login"),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salmar/hymns/models.py
import os

from django.contrib.auth.models import User
from django.core.files import File as DjangoFile
from django.db import models

from lilypond import Lilypond


class Hymn(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, blank=True, null=True)
    lyrics = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User)
    published = models.BooleanField(default=True)

    def _get_file(self, ext):
        cache_key = '_CACHE_%s' % ext
        if not hasattr(self, cache_key):
            file_object = File.objects.get(uploaded_file__endswith='.%s' % ext,
                                           hymn=self)
            setattr(self, cache_key, file_object)
        return getattr(self, cache_key)

    def add_file(self, uploaded_file, link_to_hymn=False):

        if isinstance(uploaded_file, str):
            with open(uploaded_file, 'r') as f:
                uploaded_file = DjangoFile(f)

        file_object = File(uploaded_file=uploaded_file, hymn=self,
                           link_to_hymn=link_to_hymn)
        file_object.save()
        return file_object

    def compile_lilypond(self, file_object):
        lilypond_file = Lilypond(file_object.uploaded_file.path)

        for ft in ('midi', 'pdf',):
            file_path = getattr(lilypond_file, 'get_%s' % ft)()
            file_object = self.add_file(file_path, True)
            file_object.save()

        for ft in ('png', 'ogg', 'mp3',):
            file_path = getattr(lilypond_file, 'get_%s' % ft)()
            file_object = self.add_file(file_path, False)
            file_object.save()

    def ly(self):
        return self._get_file('ly')

    def pdf(self):
        return self._get_file('pdf')

    def midi(self):
        return self._get_file('midi')

    def png(self):
        return self._get_file('png')

    def mp3(self):
        return self._get_file('mp3')

    def ogg(self):
        return self._get_file('ogg')


class File(models.Model):
    uploaded_file = models.FileField(upload_to='hymns')
    hymn = models.ForeignKey(Hymn)
    link_to_hymn = models.BooleanField(default=True)

    def url(self):
        return '/' + os.path.relpath(self.uploaded_file.url)

salmar/hymns/forms.py
from django import forms
from django.utils.translation import ugettext as _

from models import Hymn


class HymnForm(forms.ModelForm):

    lilypond_file = forms.FileField()

    class Meta:
        model = Hymn
        exclude = ['lyrics', 'creator']
        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': _('Title'),
                'autofocus': 'autofocus'
            }),
            'author': forms.TextInput(attrs={
                'placeholder': _('Author')
            })
        }

salmar/hymns/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404
from django.views.generic import FormView, TemplateView

from forms import HymnForm
from models import Hymn


class HymnView(TemplateView):

    template_name = 'hymn.html'

    def get(self, request, *args, **kwargs):
        context = {'hymns': Hymn.objects.all().order_by('-created')}
        if 'hymn_id' in self.kwargs:
            try:
                context['hymn'] = Hymn.objects.get(id=self.kwargs['hymn_id'])
            except ObjectDoesNotExist:
                raise Http404
        else:
            try:
                context['hymn'] = Hymn.objects.latest('created')
            except ObjectDoesNotExist:
                context['hymn'] = None

        return self.render_to_response(context)


class HymnFormView(FormView):

    template_name = 'hymn_form.html'
    form_class = HymnForm
    hymn = None

    def get_context_data(self, **kwargs):
        kwargs = super(HymnFormView, self).get_context_data(**kwargs)

        if 'hymn_id' in self.kwargs:
            if not self.hymn:
                try:
                    self.hymn = Hymn.objects.get(id=self.kwargs['hymn_id'])
                except ObjectDoesNotExist:
                    raise Http404
            kwargs.update({'hymn': self.hymn})
        return kwargs

    def get_form_kwargs(self):
        kwargs = super(HymnFormView, self).get_form_kwargs()
        if 'hymn_id' in self.kwargs:
            if not self.hymn:
                try:
                    self.hymn = Hymn.objects.get(id=self.kwargs['hymn_id'])
                except ObjectDoesNotExist:
                    raise Http404
            kwargs.update({'instance': self.hymn})
        return kwargs

    def get_form(self, form_class):
        form = super(HymnFormView, self).get_form(form_class)
        if 'hymn_id' in self.kwargs:
            form.fields['lilypond_file'].required = False
        return form

    def form_valid(self, form):
        form.instance.creator = self.request.user
        hymn = form.save()
        self.hymn_id = hymn.id

        if 'hymn_id' not in self.kwargs:  # If not editing existing
            lilypond_file = self.request.FILES.get('lilypond_file')
            file_object = hymn.add_file(lilypond_file, True)
            hymn.compile_lilypond(file_object)
        return super(HymnFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('view_hymn', args=(self.hymn_id,))

salmar/salmar/views.py
from django.contrib.auth.views import logout
from django.contrib.auth.views import login
from django.shortcuts import redirect


def login_user(request, page):

    response = login(request, template_name='login.html')

    if request.user.is_authenticated():
        return redirect('/%s' % page)

    return response


def logout_user(request):
    logout(request)
    return redirect(request.GET.get('next', '/'))

salmar/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% trans "Hymns music sheets" %}</title>

        <!-- Load jQuery -->
        <script src="{% static 'lib/jQuery/jquery-2.0.3.min.js' %}" type="text/javascript"></script>

        <!-- Load Foundation css -->
        <link href="{% static 'lib/foundation-5.0.2/css/foundation.min.css' %}" type="text/css" rel="stylesheet" />
        <link href="{% static 'lib/foundation-5.0.2/css/normalize.css' %}" type="text/css" rel="stylesheet" />

        <!-- Load jPlayer -->
        <link rel="stylesheet" href="{% static 'lib/circleplayer/circle.skin/circle.player.css' %}">
        <script type="text/javascript" src="{% static 'lib/circleplayer/js/jquery.transform2d.js' %}"></script>
        <script type="text/javascript" src="{% static 'lib/circleplayer/js/jquery.grab.js' %}"></script>
        <script type="text/javascript" src="{% static 'lib/circleplayer/js/jquery.jplayer.js' %}"></script>
        <script type="text/javascript" src="{% static 'lib/circleplayer/js/mod.csstransforms.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'lib/circleplayer/js/circle.player.js' %}"></script>

        <!-- Custom -->
        <link href="{% static 'css/styles.css' %}" type="text/css" rel="stylesheet" />
        <script src="{% static 'js/salmar.js' %}" type="text/javascript"></script>
    </head>
    <body>
        <!-- Load Foundation js. Must be loaded inside body because of a bug in foundation -->
        <script src="{% static 'lib/foundation-5.0.2/js/foundation.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'lib/foundation-5.0.2/js/modernizr.js' %}" type="text/javascript"></script>
        <div class="off-canvas-wrap"><div class="inner-wrap">
        <header>
            <div class="row">
                {% if hymn %}
                <div class="large-6 medium-5 small-6 columns module">
                    <span class="module-title hide-for-small-only">{% trans 'Listen' %}</span>
                    {% include 'modules/player.html' %}
                    <div class="show-for-small-only">
                        {% include 'modules/download.html' %}
                    </div>
                </div>
                <div class="large-6 medium-5 columns module hide-for-small-only">
                    <span class="module-title">{% trans 'Download' %}</span>
                    {% include 'modules/download.html' %}
                </div>
                <div class="medium-2 small-6 columns module hide-for-large-only">
                    {% include 'modules/actions.html' %}
                </div>
                {% else %}
                    <div class="columns module">
                        <a href="{% url 'hymn' %}">
                            <span class="module-title">{% trans 'Home' %}</span>
                        </a>
                    </div>
                {% endif %}
            </div>
        </header>
        <section role="main">
            <div class="row">
                <aside class="right-off-canvas-menu">
                    {% include 'sidebar/hymns_bar.html' %}
                </aside>
                {% block content %}
                {% endblock %}
            </div>
        </section>
        </div></div>
    </body>
</html>

salmar/templates/hymn.html
{% extends 'hymn_base.html' %}
{% load i18n %}

{% block hymn %}
<div class="hymn">
    {% if hymn %}
        {% if user.is_authenticated %}
        <div class="actions-bar">
            <ul class="actions">
                <li><a href="{% url 'add_hymn' %}">{% trans 'New' %}</a></li>
                <li><a href="{% url 'edit_hymn' hymn.id %}">{% trans 'Edit' %}</a></li>
                <li><a href="{% url 'logout' %}">{% trans 'Logout' %}</a></li>
            </ul>
        </div>
        {% endif %}
        <img src={{ hymn.png.url }} alt="{% trans 'Hymn chords' %}" />
    {% else %}
        No hymns have been added yet
    {% endif %}
</div>
{% endblock %}

salmar/templates/hymn_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="large-9 columns">
        {% block hymn %}
        {% endblock %}
    </div>
    <div class="large-3 columns show-for-large-only">
        {% include 'sidebar/hymns_bar.html' %}
    </div>
{% endblock %}

salmar/templates/hymn_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="form-container">
    <h1>{% if hymn %}{% trans 'Edit' %} "{{ hymn.title }}"{% else %}{% trans 'Add hymn' %}{% endif %}</h1>
    <form enctype="multipart/form-data" method="post" action="" data-plugin="showLoaderOnSubmit">
        {% csrf_token %}

        <div class="row">
            {{ form.title }}
            {{ form.title.errors }}
        </div>

        <div class="row">
            {{ form.author }}
            {{ form.author.errors }}
        </div>

        <div class="row">
            {{ form.published }}
            <label for="id_published">{{ form.published.label }}</label>
            {{ form.published.errors }}
        </div>

        {% if not hymn %}
        <div class="row file-field">
            <label for="id_lilypond_file">{{ form.lilypond_file.label }}</label>
            {{ form.lilypond_file }}
            {{ form.lilypond_file.errors }}
        </div>
        {% endif %}

        <div class="row">
            <input type="submit" name="submit" value="{% trans 'Submit' %}" />
            <div class="loading hide">{% trans 'Please be patient. This might take some time' %}</div>
        </div>
    </form>
</div>
{% endblock %}

salmar/templates/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="form-container">
    <h1>{% trans 'Login' %}</h1>

    <form method="post">
        {% csrf_token %}
        <div class="row">
            <input type="text" maxlength="254" name="username" placeholder="{% trans 'Username' %}" autofocus= />
            {{ form.username.errors }}
        </div>
        <div class="row">
            <input type="password" name="password" placeholder="{% trans 'Password' %}" />
            {{ form.password.errors }}
        </div>

        <div class="row">
            <input type="submit" value="{% trans 'Log in' %}" />
        </div>
    </form>
</div>
{% endblock %}

salmar/templates/modules/actions.html
{% load i18n %}
<a class="right-off-canvas-toggle right">
    <span class="module-title">{% trans 'Hymns' %}</span>
</a>

salmar/templates/modules/download.html
<ul class="download-list">
    <li>
        <a href="{{ hymn.pdf.url }}">PDF</a>
    </li><li>
        <a href="{{ hymn.midi.url }}">MIDI</a>
    </li><li>
        <a href="{{ hymn.mp3.url }}">MP3</a>
    </li><li>
        <a href="{{ hymn.ogg.url }}">OGG</a>
    </li>
</ul>

salmar/templates/modules/player.html
<div class="player-outer-container" data-plugin="Player" data-mp3="{{ hymn.mp3.url }}" data-ogg="{{ hymn.ogg.url }}">
    <div class="player-inner-container">
        <div id="jquery_jplayer_1" class="cp-jplayer"></div>
        <div class="prototype-wrapper">
            <div id="cp_container_1" class="cp-container">
                <div class="cp-buffer-holder">
                    <div class="cp-buffer-1"></div>
                    <div class="cp-buffer-2"></div>
                </div>
                <div class="cp-progress-holder">
                    <div class="cp-progress-1"></div>
                    <div class="cp-progress-2"></div>
                </div>
                <div class="cp-circle-control"></div>
                <ul class="cp-controls">
                    <li><a class="cp-play" tabindex="1">play</a></li>
                    <li><a class="cp-pause" style="display:none;" tabindex="1">pause</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

salmar/templates/sidebar/hymns_bar.html
{% load i18n %}
<h3>{% trans 'All hymns' %}</h3>
<ul class="hymns">
    {% for h in hymns %}
    {% if h.published %}
    <li><a href="{% url 'view_hymn' h.id %}">
        <span class="title">{{ h.title }}</span>
        {% if h.author %}<span class="author">{{ h.author }}</span>{% endif %}
    </a></li>
    {% endif %}
    {% endfor %}
</ul>